# Use https://github.com/pages-themes/hacker 
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "franzscholz.github.io"
locale: "de-DE"
url: "http://franzscholz.github.io"
repository: "franzscholz/franzscholz.github.io"


